# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0003_auto_20171007_2156'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.Cheque')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos.FacturaCompra')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.AlterModelOptions(
            name='tipoproveedor',
            options={'verbose_name': 'Tipo de proveedor', 'verbose_name_plural': 'Tipos de proveedor'},
        ),
    ]
