# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20171007_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='completa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
