# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_facturacompra_completa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together=set([('proveedor', 'serie', 'numero')]),
        ),
    ]
