# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
            },
        ),
        migrations.CreateModel(
            name='Chequera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cantidad_cheques', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Chequera',
                'verbose_name_plural': 'Chequeras',
            },
        ),
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('titular', models.CharField(max_length=128)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.Banco')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('puede_retirar', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de cuenta bancaria',
                'verbose_name_plural': 'Tipos de cuenta bancaria',
            },
        ),
        migrations.AddField(
            model_name='cuentabanco',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.CuentaBancoTipo'),
        ),
        migrations.AddField(
            model_name='chequera',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.CuentaBanco'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='chequera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.Chequera'),
        ),
    ]
