# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Depósito bancario',
                'verbose_name_plural': 'Depósitos bancarios',
            },
        ),
        migrations.AddField(
            model_name='cheque',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='nombre',
            field=models.CharField(default='', max_length=128, verbose_name='A nombre de'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheque',
            name='chequera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='bancos.Chequera'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='chequera',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chequeras', to='bancos.CuentaBanco'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='bancos.Banco'),
        ),
        migrations.AlterUniqueTogether(
            name='cheque',
            unique_together=set([('chequera', 'numero')]),
        ),
        migrations.AddField(
            model_name='depositobanco',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='bancos.CuentaBanco'),
        ),
    ]
