# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0002_auto_20171007_1440'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chequera',
            unique_together=set([('cuenta', 'numero')]),
        ),
    ]
