# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('depreciacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Depreciación')),
                ('activo_fijo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
            },
        ),
    ]
